dist: xenial
env: 
- DJANGO=2.0
before_script:
- python manage.py makemigrations
- CHROME_MAIN_VERSION=`google-chrome-stable --version | sed -E 's/(^Google Chrome |\.[0-9]+ )//g'`
- CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAIN_VERSION"`
- curl "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
- unzip chromedriver_linux64.zip -d ~/bin
language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
script:
- cd covid19analyzer
- cp travis_local_settings.py local_settings.py
- cd ..
- coverage run --branch --source=. ./manage.py test
deploy:
- provider: heroku
  app: covid-19analytics
  strategy: git
  api_key: $HEROKU_AUTH_TOKEN
  on:
    branch: develop