language: python 
python: 
- "3.8"
env: 
- DJANGO=2.0
before_install: 
- cd covid19analyzer
install: 
- pip install -r ../requirements.txt
#script: 
#- python manage.py test
before_script:
 - cp local_settings.travis.py local_settings.py
